environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew build --info
  - gradlew fatJar --info
  - gradlew sourcesJar --info
#

artifacts:
  - path: 'build\libs\*.jar'
    name: engine
#
